server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=ToyNJoy
    username: 'sa'
    password: '0120'
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: huangjunxi-test@foxmail.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: jtjssbnkauiweada
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: pers.keter.toynjoy.entity
  configuration:
    map-underscore-to-camel-case: true

# 显示dao 执行sql语句
logging:
  level:
    pers:
      keter:
        toynjoy:
          dao: debug

cbs:
  userImagesPath: file:/E:/MyProject/Visual_Studio/ToyNJoy_Server/ToyNJoy.API/Image/user/
  productImagesPath: file:/E:/MyProject/Visual_Studio/ToyNJoy_Server/ToyNJoy.API/Image/products/
  photoGalleryImagesPath: file:/E:/MyProject/Visual_Studio/ToyNJoy_Server/ToyNJoy.API/Image/PhotoGallery/